.TH XSETTINGSD 1
.SH NAME
xsettingsd \- provides settings to X11 applications
.SH SYNOPSIS
.B xsettingsd
.RI [ options ]
.SH DESCRIPTION
xsettingsd is a daemon that implements the XSETTINGS specification.  The
typical invocation is from a user's \fB~/.xsession\fR file.
.PP
It is intended to be small, fast, and minimally dependent on other
libraries. It can serve as an alternative to gnome-settings-daemon for
users who are not using the GNOME desktop environment but who still run
GTK+ applications and want to configure things such as themes, font
antialiasing/hinting, and UI sound effects.
.PP
Additional documentation is available at the project's website:
\fIhttps://github.com/derat/xsettingsd\fR
.SH OPTIONS
.TP
\fB\-c\fR, \fB\-\-config\fR=\fIFILE\fR
Load settings from \fIFILE\fR (default is \fB~/.xsettingsd\fR).
.TP
\fB\-h\fR, \fB\-\-help\fR
Display a help message and exit.
.TP
\fB\-s\fR, \fB\-\-screen\fR=\fISCREEN\fR
Use the X screen numbered \fISCREEN\fR (default of -1 means all screens).
.SH BUGS
\fIhttps://github.com/derat/xsettingsd/issues\fR
.SH EXAMPLE
Running \fIdump_xsettings\fR(1) while another XSETTINGS daemon, such as
\fBgnome-settings-daemon\fR, is already running will print your current
settings in \fBxsettingsd\fR's configuration file format.
.PP
Here is a short example \fB~/.xsettingsd\fR file:
.PP
.nf
Net/ThemeName "Human"
Xft/Antialias 1
Xft/DPI 100352
Xft/HintStyle "hintfull"
Xft/Hinting 1
Xft/RGBA "none"
Xft/lcdfilter "none"
.fi
.SH SEE ALSO
\fIdump_xsettings\fR\|(1)
.SH AUTHOR
xsettingsd was written by Daniel Erat <dan@erat.org>.
